import React from "react";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Link from "next/link";
import { useStateValue } from "../context/StateProvider";

const Enter_Your_name = () => {
  const [, dispatch] = useStateValue();
  const [gender, setGender] = useState("");
  const [nameInput, setNameInput] = useState("");
  const handleNameInput = (e) => {
    setNameInput(e.target.value);
  };

  // Dispatching data to the data layer when the user clicked the nav button
  const handleDispatch = () => {
    dispatch({
      type: "SET_NAME",
      name: nameInput,
    });
    dispatch({
      type: "SET_GENDER",
      gender: gender,
    });
  };

  // preventing page to reload after submission
  const submit = (e) => {
    e.preventDefault();
  };
  return (
    <div className="min-h-screen bg-[url('/Rectangle.png')] bg-no-repeat bg-left-bottom bg-[length:100%_auto] md:bg-[length:100%_50%]  bg-white realtive">
      <Head>
        <title>Enter Your Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* --------------------------NAV BUTTON------------------------------------------------ */}

      <div className="pt-[30px] md:pt-[50px] flex justify-end mr-[30px] ml-[30px] md:mr-[200px] md:ml-[200px]">
        <Link href="/Where_Can_We_Reach_You">
          <button
            className={`flex items-center justify-center background_navbutton h-[42px] w-[42px] md:h-[46px] md:w-[46px] 2xl:h-[55px] 2xl:w-[55px] rounded-full box-shadow_button 
             ${nameInput && gender ? "cursor-pointer" : "cursor-not-allowed"}
            `}
            disabled={nameInput && gender ? false : true}
            onClick={handleDispatch}
          >
            <img
              src="/Vector.svg"
              alt="ChevronRightIcon"
              className="md:h-[17.2px] h-[15px] text-[#FAFAFA]"
            />
          </button>
        </Link>
      </div>

      {/* ------------------------KNOW YOU BETTER------------------------------------------ */}

      <div className=" ml-[30px] mt-[4.66px] md:mt[10px] md:ml-[200px] ">
        <p className="font-normal text-[12px] leading-[18px] text-[#6776FF] mb-3 md:mb-4">
          Help us know you better!
        </p>
        <div className="  relative w-fit">
          <div className="w-fit flex items-start space-x-[32px] ">
            <div className=" z-10 w-[17.99px] h-[18px] rounded-full background-linear-blue text-center text-[12px] leading-[18px] font-semibold text-[#FAFAFA] ">
              1
            </div>
            <div className="z-10 w-[17.99px] h-[18px] rounded-full bg-[#C4C4C4] text-center text-[12px] leading-[18px] font-semibold text-[#FAFAFA] ">
              2
            </div>
            <div className=" z-10 w-[17.99px] h-[18px] rounded-full bg-[#C4C4C4] text-center text-[12px] leading-[18px] font-semibold text-[#FAFAFA] ">
              3
            </div>
          </div>
          <div className="absolute z-0 border border-dashed border-[#C4C4C4] w-full h-0 top-2/4"></div>
        </div>
      </div>

      {/* --------------------------WHAT SHOULD WE CALL YOU ----------------------------------------- */}

      <div className="ml-[30px] mt-[30px] md:mt-[37.16px] md:mr-[200px] md:ml-[200px] relative z-[5]">
        <h1 className="mb-3 font-semibold text-[18px] relative  leading-[27px] md:leading-[130%] md:mb-4 text-[#1A1A1A] ">
          What should we call you?{" "}
          <span className="absolute -top-[6px] -ml-[6px] transform rotate-12 ">
            {" "}
            <Image
              src="/Sparkle.svg"
              alt=""
              layout="fixed"
              height={18}
              width={18}
            />{" "}
          </span>{" "}
        </h1>
        {/* -------------------------NAME INPUT FORM--------------------------------------------- */}

        <form>
          <div className="">
            <input
              type="text"
              placeholder="Enter your name"
              name="Name"
              value={nameInput}
              required
              className="box-shadow_input h-10 w-[300px] bg-[#F4F4F5] border-solid border border-[#cacaca] rounded-[10px] focus:outline-none pt-[8px] pb-[8px] pl-[16px] pr-[16px] gap-[10px] md:pt-[10px] md:pb-[10px] md:pr-[20.64] md:pl-[20.64px] text-base font-medium text-[#1A1A1A] md:text-[14px] md:leading-[21px] "
              onChange={(e) => {
                handleNameInput(e);
              }}
            />
          </div>
          <button type="submit" className="hidden" onClick={submit}></button>
        </form>

        {/* -----------------------GENDER--------------------------------------------- */}

        <div className="mt-[23.04px] md:mt-[32px]">
          <h1 className="mb-3 font-semibold text-[18px] relative text-[#1A1A1A] leading-[27px] md:leading-[130%] md:mb-4">
            Gender{" "}
            <span className="absolute -top-[6px] -ml-[6px] transform rotate-12 ">
              {" "}
              <Image
                src="/Sparkle.svg"
                alt=""
                layout="fixed"
                height={18}
                width={18}
              />{" "}
            </span>{" "}
          </h1>
          {/* -------------------------GENDER BUTTONS-------------------------------------- */}

          <div className=" flex space-x-[12px] ">
            <button
              className={`flex items-center justify-center bg-white w-[69px] h-[69px] md:w-[64px] md:h-[64px]  p-3 gap-2 rounded-[10px] cursor-pointer ${
                !gender || gender == "female"
                  ? "box-shadow_frame"
                  : gender == "male"
                  ? "background_framer_selected"
                  : ""
              }`}
              onClick={() => {
                setGender("male");
              }}
            >
              <img
                className=" w-[45px] h-[45px] md:w-[40px] md:h-[40px]"
                src="/man standing.svg"
                alt="man standing"
              />
            </button>
            <button
              className={` flex items-center justify-center bg-white w-[69px] h-[69px] md:w-[64px] md:h-[64px] p-3 gap-2 rounded-[10px] cursor-pointer ${
                !gender || gender == "male"
                  ? "box-shadow_frame"
                  : gender == "female"
                  ? "background_framer_selected"
                  : ""
              } `}
              onClick={() => {
                setGender("female");
              }}
            >
              {" "}
              <img
                className=" w-[45px] h-[45px] md:w-[40px] md:h-[40px] "
                src="/young woman in pink shirt standing.svg"
                alt="young woman in pink shirt standing"
              />
            </button>
          </div>
        </div>
      </div>

      {/* --------------------------IMAGE--------------------------------------------------- */}

      <div className="absolute bottom-0 w-[100vw] m-[auto]  md:mt-[30px] md:-ml-[20px] flex justify-center z-0">
        <img
          src="/businessman in dark blue suit waving hello.png"
          alt="businessman in dark blue suit waving hello"
          className="w-[194px] h-[225px] 2xl:w-[358px] 2xl:h-[411px] "
        />
      </div>
    </div>
  );
};

export default Enter_Your_name;
