import React from "react";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

import Link from "next/link";

const Enter_Your_otp = () => {
  const [OTP1Input, setOTP1Input] = useState("");
  const [OTP2Input, setOTP2Input] = useState("");
  const [OTP3Input, setOTP3Input] = useState("");
  const [OTP4Input, setOTP4Input] = useState("");
  const [validInput, setValidInput] = useState(false);

  // checking if all the 4 OTP input boxes are filled or not
  const checkValidity = () => {
    OTP1.value.length &&
    OTP2.value.length &&
    OTP3.value.length &&
    OTP4.value.length
      ? setValidInput(true)
      : setValidInput(false);
  };

  // only accepting number in the 1st OTP input box
  const OTP1checkNumber = (e) => {
    if (e.target.value >= 0 && e.target.value <= 9) {
      setOTP1Input(e.target.value);
    } else {
      setOTP1Input("");
    }
  };

  // only accepting number in the 2nd OTP input box
  const OTP2checkNumber = (e) => {
    if (e.target.value >= 0 && e.target.value <= 9) {
      setOTP2Input(e.target.value);
    } else {
      setOTP2Input("");
    }
  };

  // only accepting number in the 3rd OTP input box
  const OTP3checkNumber = (e) => {
    if (e.target.value >= 0 && e.target.value <= 9) {
      setOTP3Input(e.target.value);
    } else {
      setOTP3Input("");
    }
  };

  // only accepting number in the 4th OTP input box
  const OTP4checkNumber = (e) => {
    if (e.target.value >= 0 && e.target.value <= 9) {
      setOTP4Input(e.target.value);
    } else {
      setOTP4Input("");
    }
  };

  // preventing page to reload after submission
  const submit = (e) => {
    e.preventDefault();
  };
  return (
    <div className="min-h-screen bg-[url('/Rectangle.png')] bg-no-repeat bg-left-bottom bg-[length:100%_auto] md:bg-[length:100%_50%]  bg-white realtive">
      <Head>
        <title>Sign up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* -------------------------NAV BUTTON--------------------------------------------- */}

      <div className="pt-[30px] md:pt-[50px] flex justify-end mr-[30px] ml-[30px] md:mr-[200px] md:ml-[200px]">
        <Link href="/Enter_Your_name">
          <button
            className={`flex items-center justify-center background_navbutton h-[42px] w-[42px] md:h-[46px] md:w-[46px] 2xl:h-[55px] 2xl:w-[55px] rounded-full box-shadow_button ${
              validInput ? "cursor-pointer" : "cursor-not-allowed"
            }`}
            disabled={!validInput ? true : false}
          >
            <img
              src="/Vector.svg"
              alt="ChevronRightIcon"
              className="md:h-[17.2px] h-[15px] text-[#FAFAFA]"
            />
          </button>
        </Link>
      </div>

      {/* ------------------------ENTER OTP------------------------------------------ */}

      <div className="ml-[30px] mt-11 md:mt-[70px] md:mr-[200px] md:ml-[200px] relative z-[5]">
        <h1 className="text-[#1A1A1A]  mb-3 font-semibold text-[24px] relative  leading-[36px] md:leading-[130%] md:mb-4">
          Enter the code{" "}
          <span className="absolute -top-[6px] -ml-[6px] transform rotate-12 ">
            {" "}
            <Image
              src="/Sparkle.svg"
              alt=""
              layout="fixed"
              height={18}
              width={18}
            />{" "}
          </span>{" "}
        </h1>
        {/* -------------------------OTP FORM--------------------------------------------- */}

        <form>
          <div className="flex space-x-[13.6px] relative w-[18.75rem] md:w-[25.75rem]">
            <input
              type="text"
              id="OTP1"
              name="OTP1"
              className="OTPInput"
              value={OTP1Input}
              pattern="[0-9]+"
              required
              maxLength={1}
              onChange={(e) => {
                OTP1checkNumber(e);
                checkValidity();
                e.target.value.length === 1 ? OTP2.focus() : "";
              }}
            />
            <input
              type="text"
              id="OTP2"
              name="OTP2"
              value={OTP2Input}
              className="OTPInput"
              pattern="[0-9]+"
              required
              maxLength={1}
              onChange={(e) => {
                OTP2checkNumber(e);
                checkValidity();
                e.target.value.length === 1 ? OTP3.focus() : "";
                e.target.value.length === 0 ? OTP1.focus() : "";
              }}
            />
            <input
              type="text"
              id="OTP3"
              name="OTP3"
              value={OTP3Input}
              className="OTPInput"
              pattern="[0-9]+"
              required
              maxLength={1}
              onChange={(e) => {
                OTP3checkNumber(e);
                checkValidity();
                e.target.value.length === 1 ? OTP4.focus() : "";
                e.target.value.length === 0 ? OTP2.focus() : "";
              }}
            />
            <input
              type="text"
              id="OTP4"
              name="OTP4"
              value={OTP4Input}
              className="OTPInput"
              pattern="[0-9]+"
              required
              maxLength={1}
              onChange={(e) => {
                OTP4checkNumber(e);
                checkValidity();
                e.target.value.length === 0 ? OTP3.focus() : "";
              }}
            />
          </div>
          <button type="submit" className="hidden" onClick={submit}></button>
        </form>
        {/* -------------------------RESEND THE CODE--------------------------------------------- */}

        <div>
          <Link href="#">
            <a className="mt-[12px] font-semibold text-sm md:text-[12px] md:leading-[20px] text-[#6776FF] underline tracking-[1px]">
              Resend the code
            </a>
          </Link>
        </div>
      </div>
      {/* --------------------------IMAGE--------------------------------------------------- */}

      <div className="absolute bottom-0 w-[100vw] m-[auto]  md:mt-[30px] md:-ml-[20px] flex justify-center z-0">
        <img
          src="/Notifications.png"
          alt="Notifications"
          className="w-[319px] h-[288px] 2xl:w-[568px] 2xl:h-[513px] "
        />
      </div>
    </div>
  );
};

export default Enter_Your_otp;
