import React from "react";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

import Link from "next/link";
import { useStateValue } from "../context/StateProvider";

const Where_Can_I_Reach_You = () => {
  const [, dispatch] = useStateValue();
  const [emailInput, setEmailInput] = useState("");
  const [validEmail, setValidEmail] = useState(false);
  const [unselectedCities, setUnselectedCities] = useState([
    "Mumbai",
    "Bangaluru",
    "Delhi",
    "Pune",
  ]);
  const [preferredCities, setPreferredCities] = useState();

  // checks email input validity and add input to state
  const handleEmailInput = (e) => {
    setEmailInput(e.target.value);
    setValidEmail(email.checkValidity());
  };

  // Dispatching data to Data Layer when the user clicked the nav bar
  const handleDispatch = () => {
    dispatch({
      type: "SET_EMAIL",
      email: emailInput,
    });
    dispatch({
      type: "SET_PREFERRED-CITY",
      preferred_City: preferredCities,
    });
  };

  // preventing page to reload after submission
  const submit = (e) => {
    e.preventDefault();
  };
  return (
    <div className="min-h-screen bg-[url('/Rectangle.png')] bg-no-repeat bg-left-bottom bg-[length:100%_auto] md:bg-[length:100%_50%]  bg-white realtive">
      <Head>
        <title>Where can I reach you</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* --------------------------Nav Button --------------------------------------------------- */}

      <div className="pt-[30px] md:pt-[50px] flex justify-end mr-[30px] ml-[30px] md:mr-[200px] md:ml-[200px]">
        <Link href="/What_is_Your_Role">
          <button
            className={`flex items-center justify-center background_navbutton h-[42px] w-[42px] md:h-[46px] md:w-[46px] 2xl:h-[55px] 2xl:w-[55px] rounded-full box-shadow_button 
            // ${
              validEmail && preferredCities
                ? "cursor-pointer"
                : "cursor-not-allowed"
            }
            `}
            disabled={validEmail && preferredCities ? false : true}
            onClick={handleDispatch}
          >
            <img
              src="/Vector.svg"
              alt="ChevronRightIcon"
              className="md:h-[17.2px] h-[15px] text-[#FAFAFA]"
            />
          </button>
        </Link>
      </div>
      {/* --------------------------Know you better--------------------------------------------------- */}

      <div className=" ml-[30px] mt-[4.66px] md:mt[10px] md:ml-[200px] ">
        <p className="font-normal text-[12px] leading-[18px] text-[#6776FF] mb-3 md:mb-4">
          Help us know you better!
        </p>
        <div className="  relative w-fit">
          <div className="w-fit flex items-start space-x-[32px] ">
            <div className=" z-10 w-[17.99px] h-[18px] rounded-full background-linear-blue text-center text-[12px] leading-[18px] font-semibold text-[#FAFAFA] ">
              1
            </div>
            <div className="z-10 w-[17.99px] h-[18px] rounded-full background-linear-blue text-center text-[12px] leading-[18px] font-semibold text-[#FAFAFA] ">
              2
            </div>
            <div className=" z-10 w-[17.99px] h-[18px] rounded-full bg-[#C4C4C4] text-center text-[12px] leading-[18px] font-semibold text-[#FAFAFA] ">
              3
            </div>
          </div>
          <div className="absolute z-0 border border-dashed border-[#C4C4C4] w-1/2 h-0 top-2/4 left-1/2"></div>
          <div className="absolute z-0 border border-dashed border-[#6776FF] w-1/2 h-0 top-1/2 "></div>
        </div>
      </div>

      {/* --------------------------EMAIL FORM --------------------------------------------------- */}

      <div className="ml-[30px] mt-[30px] md:mt-[25.16px] md:mr-[200px] md:ml-[200px] relative z-[5]">
        <h1 className="mb-3 font-semibold text-[18px] relative  leading-[27px] md:leading-[130%] md:mb-3 text-[#1A1A1A] ">
          Where can we reach you?{" "}
          <span className="absolute -top-[6px] -ml-[6px] transform rotate-12 ">
            {" "}
            <Image
              src="/Sparkle.svg"
              alt=""
              layout="fixed"
              height={18}
              width={18}
            />{" "}
          </span>{" "}
        </h1>
        <form>
          <div className="">
            <input
              type="email"
              placeholder="Enter your email id"
              id="email"
              pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$"
              name="Email"
              value={emailInput}
              required
              className="box-shadow_input h-10 w-[300px] bg-[#F4F4F5] border-solid border border-[#cacaca] rounded-[10px] focus:outline-none pt-[8px] pb-[8px] pl-[16px] pr-[16px] gap-[10px] md:pt-[10px] md:pb-[10px] md:pr-[20.64] md:pl-[20.64px] text-base font-medium text-[#1A1A1A] md:text-[14px] md:leading-[21px] "
              onChange={(e) => {
                handleEmailInput(e);
              }}
            />
          </div>
          <button type="submit" className="hidden" onClick={submit}></button>
        </form>

        {/* --------------------------PREFERRED CITY INPUT--------------------------------------------------- */}

        <div className="mt-[28px] md:mt-[25px]">
          <h3 className="mb-3 font-semibold text-[18px] relative text-[#1A1A1A] leading-[27px] md:leading-[130%] md:mb-3">
            Preferred city to work{" "}
            <span className="absolute -top-[6px] -ml-[6px] transform rotate-12 ">
              {" "}
              <Image
                src="/Sparkle.svg"
                alt=""
                layout="fixed"
                height={18}
                width={18}
              />{" "}
            </span>{" "}
          </h3>
          <div className=" flex items-center justify-center box-shadow_input h-10 w-[300px] bg-[#F4F4F5] border-solid border border-[#cacaca] rounded-[10px] ">
            <input
              placeholder="Eg.Bengaluru,Mumbai"
              name="Preferred city"
              required
              disabled
              className="flex-grow focus:outline-none pt-[8px] pb-[8px] pl-[16px] pr-[16px] gap-[10px] md:pt-[10px] md:pb-[10px] md:pr-[20.64] md:pl-[20.64px] text-base font-medium text-[#1A1A1A] md:text-[14px] md:leading-[21px] "
            />
            <img
              src="/ChevronDownIcon.svg"
              alt=""
              className=" w-[12.02px] h-[6px] m-[17px]"
            />
          </div>
        </div>

        {/* --------------------------PREFERRED CITY----------------------------------------------- */}

        <div className="mt-2 flex space-x-[12px] max-w-[80vw]">
          {preferredCities && (
            <button
              className={` flex items-center justify-between w-[124px] h-8 background_city_selected rounded-[10px] pt-[4px] pb-[4px] pr-[8px] pl-[8px] text-base font-medium text-[#FAFAFA] text-center  cursor-default whitespace-nowrap`}
            >
              <div className="flex items-center justify-between w-full">
                <span>{preferredCities}</span>
                <div
                  className="bg-[#FAFAFA] w-[23px] h-[23px] rounded-full box-shadow_button text-center text-[#6776FF] font-semibold cursor-pointer"
                  onClick={() => {
                    setPreferredCities();
                  }}
                >
                  x
                </div>
              </div>
            </button>
          )}
        </div>

        {/* --------------------------TOP CITIES --------------------------------------------------- */}

        <div className="mt-3">
          <h3 className="mb-1 font-medium text-[14px] relative text-black leading-[20px] lg:mb-2 tracking-[1px]">
            Top cities you may preferred:{" "}
          </h3>
          <div className="mt-[4px] flex space-x-[12px]  max-w-[80vw]">
            {unselectedCities.map((city, index) => (
              <div className="cursor-pointer" key={index}>
                <button
                  className={` cursor-pointer  h-10 bg-white rounded-[10px] box-shadow_cities pt-[10px] pb-[10px] pr-[8px] pl-[8px] text-sm font-medium text-[#6776FF] text-center tracking-[1px] ${
                    city == "Pune" ? "hidden md:block" : ""
                  } `}
                  onClick={() => {
                    setPreferredCities(city);
                  }}
                >
                  {city}
                </button>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* --------------------------IMAGE--------------------------------------------------- */}

      <div className="absolute bottom-0 w-[90vw] m-[auto]  lg:justify-center lg:ml-20 flex justify-end z-0">
        <img
          src="/black location tag.png"
          alt="black location tag"
          className="w-[161px] h-[187px] 2xl:w-[358px] 2xl:h-[411px] "
        />
      </div>
    </div>
  );
};

export default Where_Can_I_Reach_You;
